server:
  port: 8081
  servlet:
    context-path: /api/vehicle

spring:
  application:
    name: xiaomi-vehicle-service
  profiles:
    active: dev

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.50.131:3306/xiaomi_battery?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: MySQL-123

  # Redis配置
  data:
    redis:
      host: 192.168.50.131
      port: 6379
      password:
      database: 0
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaomi.vehicle.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# Dubbo配置
dubbo:
  application:
    name: xiaomi-vehicle-service
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.xiaomi.vehicle.provider

# 日志配置
logging:
  level:
    com.xiaomi.vehicle.mapper: debug
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://192.168.50.131:3306/xiaomi_battery?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
  data:
    redis:
      host: 192.168.50.131

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://prod-mysql:3306/xiaomi_battery?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
  data:
    redis:
      host: prod-redis